### ISSUE TITLE
‘lmo_test' is empty

### ISSUE THREAD

**Issue by RainYQ** [THU-DA-6D-Pose-Group/GDR-Net#20]
Run evaluation sample
```
./core/gdrn_modeling/test_gdrn.sh configs/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e.py 0 output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/gdrn_lmo_real_pbr.pth
```
got error like:
```
[07/08 11:08:34 fvcore.common.checkpoint]: [Checkpointer] Loading from output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/gdrn_lmo_real_pbr.pth ...
[0708_110834 core.gdrn_modeling.gdrn_custom_evaluator@98]: eval precision: False
[0708_110834 core.gdrn_modeling.datasets.lm_dataset_d2@97]: loading dataset dicts: lmo_test
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1214/1214 [00:00<00:00, 13442.86it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  8.74it/s]
[0708_110835 core.gdrn_modeling.datasets.lm_dataset_d2@219]: loaded 0 dataset dicts, using 0.12068194802850485s
[0708_110835 core.gdrn_modeling.datasets.lm_dataset_d2@223]: Dumped dataset_dicts to /home/rainyq/GDR-Net/.cache/dataset_dicts_lmo_test_f1f941cbcce3a9bc511361b5064d58cf.pkl
Traceback (most recent call last):
  File "core/gdrn_modeling/main_gdrn.py", line 153, in <module>
    launch(
  File "/home/rainyq/.local/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "core/gdrn_modeling/main_gdrn.py", line 114, in main
    return do_test(cfg, model)
  File "/home/rainyq/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/engine.py", line 127, in do_test
    data_loader = build_gdrn_test_loader(cfg, dataset_name, train_objs=evaluator.train_objs)
  File "/home/rainyq/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/data_loader.py", line 721, in build_gdrn_test_loader
    dataset_dicts = get_detection_dataset_dicts(
  File "/home/rainyq/.local/lib/python3.8/site-packages/detectron2/data/build.py", line 229, in get_detection_dataset_dicts
    assert len(dicts), "Dataset '{}' is empty!".format(dataset_name)
AssertionError: Dataset 'lmo_test' is empty!
```
It looks like  that 'lmo_test' dataset was not successfully registered.
What should me do?

**Comment by wangg12** [comment]
Perhaps you didn't prepare the dataset correctly. I cannot tell what the problem is given the limited information.

**Comment by saintrealchoi** [comment]
I have the same problem.
And I solve it.
I have an error for building lmo_test dataset. because I didnt download lmo dataset.
you should lmo dataset.

when i download LM dataset,
```
export SRC=https://bop.felk.cvut.cz/media/data/bop_datasets
wget $SRC/lm_base.zip         # Base archive with dataset info, camera parameters, etc.
wget $SRC/lm_models.zip       # 3D object models.
wget $SRC/lm_test_all.zip     # All test images ("_bop19" for a subset used in the BOP Challenge 2019/2020).
wget $SRC/lm_train_pbr.zip    # PBR training images (rendered with BlenderProc4BOP).

unzip lm_base.zip             # Contains folder "lm".
unzip lm_models.zip -d lm     # Unpacks to "lm".
unzip lm_test_all.zip -d lm   # Unpacks to "lm".
unzip lm_train_pbr.zip -d lm  # Unpacks to "lm".
```

and I **DONOT** download lmo dataset.
If you command `wget lmo_base.zip`. you will download lmo dataset.

and it will be fixed
