### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'NAME'

### ISSUE THREAD

**Issue by INGnowait** [THU-DA-6D-Pose-Group/GDR-Net#34]
您好，我在train的时候，出现了以下的问题：

Traceback (most recent call last):
  File "main_gdrn.py", line 159, in <module>
    args=(args,),
  File "/home/j/anaconda3/envs/6Dpose/lib/python3.7/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "main_gdrn.py", line 108, in main
    logger.info(f"Used CDPN module name: {cfg.MODEL.CDPN.NAME}")
  File "/home/j/anaconda3/envs/6Dpose/lib/python3.7/site-packages/mmcv/utils/config.py", line 36, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'NAME'

应该是mmcv版本过高导致的，但是我试过所有mmcv的版本都不行。这种情况有解决方法吗？我的pytroch版本是1.9.0。

**Comment by wangg12** [comment]
你自己定义的cfg还是？

**Comment by INGnowait** [comment]
用的是SO-Pose code，就只更改了数据集路径，用的还是code中的cfg，运行GDR-Net的时候出现的这个问题(并没有运行SO-pose）。

**Comment by wangg12** [comment]
用这个仓库的code吧
