### ISSUE TITLE
an assertionError occured when I run evaluation with the example command provided in README.md, seem like there is a file or what missing

### ISSUE THREAD

**Issue by Hsuweehou** [THU-DA-6D-Pose-Group/GDR-Net#35]
paste the error log below
help me with this, please!

(GDR-Net) t@linux:~/PycharmProjects/GDR-Net$ ./core/gdrn_modeling/test_gdrn.sh configs/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e.py 0 output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/gdrn_lmo_real_pbr.pth
+ CFG=configs/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e.py
+ CUDA_VISIBLE_DEVICES=0
+ IFS=,
+ read -ra GPUS
+ NGPU=1
+ echo 'use gpu ids: 0 num gpus: 1'
use gpu ids: 0 num gpus: 1
+ CKPT=output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/gdrn_lmo_real_pbr.pth
+ NCCL_DEBUG=INFO
+ OMP_NUM_THREADS=1
+ MKL_NUM_THREADS=1
+ CUDA_VISIBLE_DEVICES=0
+ python core/gdrn_modeling/main_gdrn.py --config-file configs/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e.py --num-gpus 1 --eval-only --opts MODEL.WEIGHTS=output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/gdrn_lmo_real_pbr.pth
You requested to import horovod which is missing or not supported for your OS.
You requested to import horovod which is missing or not supported for your OS.
[0926_123942@core/gdrn_modeling/main_gdrn.py:133] soft limit:  500000 hard limit:  1048576
[0926_123942@core/gdrn_modeling/main_gdrn.py:137] Command Line Args: Namespace(config_file='configs/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e.py', dist_url='tcp://127.0.0.1:50152', eval_only=True, fp16_allreduce=False, machine_rank=0, num_gpus=1, num_machines=1, opts={'MODEL.WEIGHTS': 'output/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e/gdrn_lmo_real_pbr.pth'}, resume=False, use_adasum=False, use_hvd=False)
[0926_123942@core/gdrn_modeling/main_gdrn.py:72] optimizer_cfg: {'type': 'Ranger', 'lr': 0.0001, 'weight_decay': 0}
[0926_123942@core/gdrn_modeling/datasets/lm_dataset_d2.py:592] DBG register dataset: lmo_train
[0926_123942@core/gdrn_modeling/datasets/lm_dataset_d2.py:592] DBG register dataset: lmo_test
[0926_123942@core/gdrn_modeling/datasets/lm_pbr.py:399] DBG register dataset: lmo_pbr_train
Traceback (most recent call last):
  File "core/gdrn_modeling/main_gdrn.py", line 159, in <module>
    args=(args,),
  File "/home/t/.virtualenvs/GDR-Net/lib/python3.6/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "core/gdrn_modeling/main_gdrn.py", line 106, in main
    cfg = setup(args)
  File "core/gdrn_modeling/main_gdrn.py", line 84, in setup
    register_datasets_in_cfg(cfg)
  File "/home/t/PycharmProjects/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/dataset_factory.py", line 43, in register_datasets_in_cfg
    register_dataset(_mod_name, name, data_cfg=None)
  File "/home/t/PycharmProjects/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/dataset_factory.py", line 26, in register_dataset
    register_func.register_with_name_cfg(dset_name, data_cfg)
  File "/home/t/PycharmProjects/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/datasets/lm_pbr.py", line 405, in register_with_name_cfg
    DatasetCatalog.register(name, LM_PBR_Dataset(used_cfg))
  File "/home/t/PycharmProjects/GDR-Net/core/gdrn_modeling/../../core/gdrn_modeling/datasets/lm_pbr.py", line 42, in __init__
    assert osp.exists(self.dataset_root), self.dataset_root
AssertionError: /home/t/PycharmProjects/GDR-Net/datasets/BOP_DATASETS/lmo/train_pbr

**Comment by wangg12** [comment]
you need to prepare the datasets as in README.
