### ISSUE TITLE
Missed ycbv_test_targets_keyframe.json ? 

### ISSUE THREAD

**Issue by MMRobotics** [THU-DA-6D-Pose-Group/GDR-Net#54]
[1122_221500@eval_calc_errors.py:135] Processing: gdrn-selfocc-multistep-10e-test-iter0_ycbvposecnn-test.csv
[1122_221500@eval_calc_errors.py:173] Loading object models...
Traceback (most recent call last):
  File "/home/yxu/Projects/Works/SO-Pose/lib/pysixd/scripts/eval_calc_errors.py", line 234, in <module>
    targets = inout.load_json(osp.join(dp_split["base_path"], p["targets_filename"]))
  File "/home/yxu/Projects/Works/SO-Pose/lib/pysixd/scripts/../../../lib/pysixd/inout.py", line 92, in load_json
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/BOP_DATASETS/ycbv/ycbv_test_targets_keyframe.json'
Traceback (most recent call last):
  File "/home/yxu/Projects/Works/SO-Pose/lib/pysixd/scripts/eval_pose_results_more.py", line 229, in <module>
    raise RuntimeError("Calculation of pose errors failed.")
RuntimeError: Calculation of pose errors failed.
*** Error in `python': corrupted size vs. prev_size: 0x0000557828e20910 ***
WRN [1122_221502 core.gdrn_selfocc_modeling.engine.test_utils@70]: evaluation failed.
  0%|                                                                                    | 0/1 [00:00<?, ?it/s][1122_221502 core.gdrn_selfocc_modeling.engine.test_utils@274]: =====================================================================
WRN [1122_221502 core.gdrn_selfocc_modeling.engine.test_utils@316]: output/gdrn_selfocc/ycbv/pbr_13e/inference_model_final/ycbv_test/gdrn-selfocc-multistep-10e-test-iter0_ycbvposecnn-test/error:AUCadd_ntop:1 does not exist.
  0%|                                                                                    | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "core/gdrn_selfocc_modeling/main_gdrn.py", line 254, in <module>
    args=(args,),
  File "/home/yxu/miniconda3/envs/py37_tch171/lib/python3.7/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "core/gdrn_selfocc_modeling/main_gdrn.py", line 160, in main
    return do_test(cfg, model)
  File "/home/yxu/Projects/Works/SO-Pose/core/gdrn_selfocc_modeling/../../core/gdrn_selfocc_modeling/engine/engine.py", line 119, in do_test
    results_i = gdrn_inference_on_dataset(cfg, model, data_loader, evaluator, amp_test=cfg.TEST.AMP_TEST)
  File "/home/yxu/Projects/Works/SO-Pose/core/gdrn_selfocc_modeling/../../core/gdrn_selfocc_modeling/engine/gdrn_evaluator.py", line 667, in gdrn_inference_on_dataset
    results = evaluator.evaluate()  # results is always None
  File "/home/yxu/Projects/Works/SO-Pose/core/gdrn_selfocc_modeling/../../core/gdrn_selfocc_modeling/engine/gdrn_evaluator.py", line 479, in evaluate
    return self._eval_predictions()
  File "/home/yxu/Projects/Works/SO-Pose/core/gdrn_selfocc_modeling/../../core/gdrn_selfocc_modeling/engine/gdrn_evaluator.py", line 489, in _eval_predictions
    save_and_eval_results(self.cfg, results_all, self._output_dir, obj_ids=self.obj_ids)
  File "/home/yxu/Projects/Works/SO-Pose/core/gdrn_selfocc_modeling/../../core/gdrn_selfocc_modeling/engine/test_utils.py", line 73, in save_and_eval_results
    cfg, eval_root=save_root, result_names=result_names, error_types=cfg.VAL.ERROR_TYPES.split(","), obj_ids=obj_ids
  File "/home/yxu/Projects/Works/SO-Pose/core/gdrn_selfocc_modeling/../../core/gdrn_selfocc_modeling/engine/test_utils.py", line 317, in load_and_print_val_scores_tab
    raise RuntimeError("{} does not exist.".format(score_root))
RuntimeError: output/gdrn_selfocc/ycbv/pbr_13e/inference_model_final/ycbv_test/gdrn-selfocc-multistep-10e-test-iter0_ycbvposecnn-test/error:AUCadd_ntop:1 does not exist.

**Comment by wangg12** [comment]
Uploaded on NetDisk. Please find the link in README.md
